_target_: fmfourier.models.velocity_models.VelocityModule
_partial_: true
d_model: 72
num_layers: 10
n_head: 12
lr_max: 1.0e-3
fourier_noise_scaling: ${fourier_transform}

defaults:
  - path: default
