_target_: fmfourier.dataloaders.datamodules.GaussianDatamodule
data_dir: ${hydra:runtime.cwd}/data
random_seed: ${random_seed}
fourier_transform: ${fourier_transform}
standardize: ${standardize}
energy_normalization: true
batch_size: 64
std: 10